### ISSUE TITLE
It won't launch cause of missing dll

### ISSUE THREAD

**Issue by pb29** [Apfel/Ongaku-Windows#1]
it says i have no MSVCP140D.dll so i search about it and reinstall Visual C++ Redistributable Packages 2015 x64 and x32, but still not working.. help!

**Comment by Apfel** [comment]
Try [these](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) ones.

**Comment by Apfel** [comment]
Turns out we built the previous update with debug libraries by accident, sorry!
You can find the new update [here](https://github.com/Apfel/Ongaku-Windows/releases/tag/1.2.1), these ones were built with the normal version of the Redistributables.
Let me know if this update doesn't work either, I'll leave the issue open for the time being.

**Comment by pb29** [comment]
thanks, it works now with new update!
